/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type InventoryCategory = { 'other' : null } |
  { 'trim' : null } |
  { 'thread' : null } |
  { 'fabric' : null };
export interface InventoryItem {
  'id' : InventoryItemId,
  'name' : string,
  'unit' : InventoryUnit,
  'lastUpdated' : Time,
  'category' : InventoryCategory,
  'reorderLevel' : number,
  'currentStock' : number,
}
export type InventoryItemId = bigint;
export type InventoryUnit = { 'kg' : null } |
  { 'meter' : null } |
  { 'roll' : null } |
  { 'piece' : null };
export interface JobWorkAssignment {
  'id' : JobWorkAssignmentId,
  'productionJobId' : ProductionJobId,
  'status' : JobWorkAssignmentStatus,
  'actualReturnDate' : [] | [Time],
  'jobWorkerId' : JobWorkerId,
  'stage' : ProductionStage,
  'expectedReturnDate' : Time,
  'notes' : string,
  'assignedDate' : Time,
}
export type JobWorkAssignmentId = bigint;
export type JobWorkAssignmentStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'inProgress' : null } |
  { 'returned' : null };
export interface JobWorker {
  'id' : JobWorkerId,
  'name' : string,
  'contactPerson' : string,
  'isActive' : boolean,
  'specialty' : JobWorkerSpecialty,
  'phone' : string,
  'location' : string,
}
export type JobWorkerId = bigint;
export type JobWorkerSpecialty = { 'embroidery' : null } |
  { 'both' : null } |
  { 'stitching' : null };
export type OrderId = bigint;
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'dispatched' : null } |
  { 'inProduction' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'isActive' : boolean,
  'sizes' : Array<string>,
  'category' : string,
  'basePrice' : bigint,
  'material' : string,
}
export type ProductId = bigint;
export interface ProductOrder {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'customerContact' : string,
  'createdAt' : Time,
  'size' : string,
  'deliveryDate' : string,
  'productId' : ProductId,
  'orderType' : { 'MTO' : null } |
    { 'readyStock' : null },
  'notes' : string,
  'quantity' : bigint,
  'orderNumber' : string,
  'styleName' : string,
}
export interface ProductionJob {
  'id' : ProductionJobId,
  'startedAt' : Time,
  'isCompleted' : boolean,
  'stageHistory' : Array<StageHistoryEntry>,
  'orderId' : OrderId,
  'currentStage' : ProductionStage,
}
export type ProductionJobId = bigint;
export type ProductionStage = { 'embroidery' : null } |
  { 'dispatchReady' : null } |
  { 'qualityCheck' : null } |
  { 'stitching' : null } |
  { 'finishing' : null } |
  { 'cutting' : null };
export interface StageHistoryEntry {
  'completedAt' : Time,
  'stage' : ProductionStage,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'advanceProductionJobStage' : ActorMethod<
    [ProductionJobId, ProductionStage],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInventoryItem' : ActorMethod<
    [string, InventoryCategory, InventoryUnit, number, number],
    InventoryItemId
  >,
  'createJobWorkAssignment' : ActorMethod<
    [ProductionJobId, ProductionStage, JobWorkerId, Time, Time, string],
    JobWorkAssignmentId
  >,
  'createJobWorker' : ActorMethod<
    [string, JobWorkerSpecialty, string, string, string],
    JobWorkerId
  >,
  'createOrder' : ActorMethod<
    [
      string,
      string,
      string,
      ProductId,
      string,
      string,
      bigint,
      { 'MTO' : null } |
        { 'readyStock' : null },
      string,
      string,
    ],
    OrderId
  >,
  'createProduct' : ActorMethod<
    [string, string, Array<string>, string, bigint],
    ProductId
  >,
  'createProductionJob' : ActorMethod<
    [OrderId, ProductionStage],
    ProductionJobId
  >,
  'deleteInventoryItem' : ActorMethod<[InventoryItemId], undefined>,
  'deleteJobWorkAssignment' : ActorMethod<[JobWorkAssignmentId], undefined>,
  'deleteJobWorker' : ActorMethod<[JobWorkerId], undefined>,
  'deleteOrder' : ActorMethod<[OrderId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteProductionJob' : ActorMethod<[ProductionJobId], undefined>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllJobWorkAssignments' : ActorMethod<[], Array<JobWorkAssignment>>,
  'getAllJobWorkers' : ActorMethod<[], Array<JobWorker>>,
  'getAllOrders' : ActorMethod<[], Array<ProductOrder>>,
  'getAllProductionJobs' : ActorMethod<[], Array<ProductionJob>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventoryItem' : ActorMethod<[InventoryItemId], InventoryItem>,
  'getJobWorkAssignment' : ActorMethod<
    [JobWorkAssignmentId],
    JobWorkAssignment
  >,
  'getJobWorkAssignmentsByJobAndWorker' : ActorMethod<
    [ProductionJobId, JobWorkerId],
    Array<JobWorkAssignment>
  >,
  'getJobWorker' : ActorMethod<[JobWorkerId], JobWorker>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getOrder' : ActorMethod<[OrderId], ProductOrder>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<ProductOrder>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductionJob' : ActorMethod<[ProductionJobId], ProductionJob>,
  'getProductionJobsByOrderId' : ActorMethod<[OrderId], Array<ProductionJob>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'updateJobWorkAssignment' : ActorMethod<[JobWorkAssignment], undefined>,
  'updateJobWorker' : ActorMethod<[JobWorker], undefined>,
  'updateOrder' : ActorMethod<[ProductOrder], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateProductionJob' : ActorMethod<[ProductionJob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];