/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductionJobId = IDL.Nat;
export const ProductionStage = IDL.Variant({
  'embroidery' : IDL.Null,
  'dispatchReady' : IDL.Null,
  'qualityCheck' : IDL.Null,
  'stitching' : IDL.Null,
  'finishing' : IDL.Null,
  'cutting' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InventoryCategory = IDL.Variant({
  'other' : IDL.Null,
  'trim' : IDL.Null,
  'thread' : IDL.Null,
  'fabric' : IDL.Null,
});
export const InventoryUnit = IDL.Variant({
  'kg' : IDL.Null,
  'meter' : IDL.Null,
  'roll' : IDL.Null,
  'piece' : IDL.Null,
});
export const InventoryItemId = IDL.Nat;
export const JobWorkerId = IDL.Nat;
export const Time = IDL.Int;
export const JobWorkAssignmentId = IDL.Nat;
export const JobWorkerSpecialty = IDL.Variant({
  'embroidery' : IDL.Null,
  'both' : IDL.Null,
  'stitching' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const OrderId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
  'material' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : InventoryItemId,
  'name' : IDL.Text,
  'unit' : InventoryUnit,
  'lastUpdated' : Time,
  'category' : InventoryCategory,
  'reorderLevel' : IDL.Float64,
  'currentStock' : IDL.Float64,
});
export const JobWorkAssignmentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'inProgress' : IDL.Null,
  'returned' : IDL.Null,
});
export const JobWorkAssignment = IDL.Record({
  'id' : JobWorkAssignmentId,
  'productionJobId' : ProductionJobId,
  'status' : JobWorkAssignmentStatus,
  'actualReturnDate' : IDL.Opt(Time),
  'jobWorkerId' : JobWorkerId,
  'stage' : ProductionStage,
  'expectedReturnDate' : Time,
  'notes' : IDL.Text,
  'assignedDate' : Time,
});
export const JobWorker = IDL.Record({
  'id' : JobWorkerId,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'isActive' : IDL.Bool,
  'specialty' : JobWorkerSpecialty,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'dispatched' : IDL.Null,
  'inProduction' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ProductOrder = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerContact' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Text,
  'deliveryDate' : IDL.Text,
  'productId' : ProductId,
  'orderType' : IDL.Variant({ 'MTO' : IDL.Null, 'readyStock' : IDL.Null }),
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'orderNumber' : IDL.Text,
  'styleName' : IDL.Text,
});
export const StageHistoryEntry = IDL.Record({
  'completedAt' : Time,
  'stage' : ProductionStage,
});
export const ProductionJob = IDL.Record({
  'id' : ProductionJobId,
  'startedAt' : Time,
  'isCompleted' : IDL.Bool,
  'stageHistory' : IDL.Vec(StageHistoryEntry),
  'orderId' : OrderId,
  'currentStage' : ProductionStage,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'advanceProductionJobStage' : IDL.Func(
      [ProductionJobId, ProductionStage],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInventoryItem' : IDL.Func(
      [IDL.Text, InventoryCategory, InventoryUnit, IDL.Float64, IDL.Float64],
      [InventoryItemId],
      [],
    ),
  'createJobWorkAssignment' : IDL.Func(
      [ProductionJobId, ProductionStage, JobWorkerId, Time, Time, IDL.Text],
      [JobWorkAssignmentId],
      [],
    ),
  'createJobWorker' : IDL.Func(
      [IDL.Text, JobWorkerSpecialty, IDL.Text, IDL.Text, IDL.Text],
      [JobWorkerId],
      [],
    ),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Variant({ 'MTO' : IDL.Null, 'readyStock' : IDL.Null }),
        IDL.Text,
        IDL.Text,
      ],
      [OrderId],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
      [ProductId],
      [],
    ),
  'createProductionJob' : IDL.Func(
      [OrderId, ProductionStage],
      [ProductionJobId],
      [],
    ),
  'deleteInventoryItem' : IDL.Func([InventoryItemId], [], []),
  'deleteJobWorkAssignment' : IDL.Func([JobWorkAssignmentId], [], []),
  'deleteJobWorker' : IDL.Func([JobWorkerId], [], []),
  'deleteOrder' : IDL.Func([OrderId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteProductionJob' : IDL.Func([ProductionJobId], [], []),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllJobWorkAssignments' : IDL.Func(
      [],
      [IDL.Vec(JobWorkAssignment)],
      ['query'],
    ),
  'getAllJobWorkers' : IDL.Func([], [IDL.Vec(JobWorker)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(ProductOrder)], ['query']),
  'getAllProductionJobs' : IDL.Func([], [IDL.Vec(ProductionJob)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInventoryItem' : IDL.Func([InventoryItemId], [InventoryItem], ['query']),
  'getJobWorkAssignment' : IDL.Func(
      [JobWorkAssignmentId],
      [JobWorkAssignment],
      ['query'],
    ),
  'getJobWorkAssignmentsByJobAndWorker' : IDL.Func(
      [ProductionJobId, JobWorkerId],
      [IDL.Vec(JobWorkAssignment)],
      ['query'],
    ),
  'getJobWorker' : IDL.Func([JobWorkerId], [JobWorker], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getOrder' : IDL.Func([OrderId], [ProductOrder], ['query']),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(ProductOrder)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductionJob' : IDL.Func([ProductionJobId], [ProductionJob], ['query']),
  'getProductionJobsByOrderId' : IDL.Func(
      [OrderId],
      [IDL.Vec(ProductionJob)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInventoryItem' : IDL.Func([InventoryItem], [], []),
  'updateJobWorkAssignment' : IDL.Func([JobWorkAssignment], [], []),
  'updateJobWorker' : IDL.Func([JobWorker], [], []),
  'updateOrder' : IDL.Func([ProductOrder], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateProductionJob' : IDL.Func([ProductionJob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductionJobId = IDL.Nat;
  const ProductionStage = IDL.Variant({
    'embroidery' : IDL.Null,
    'dispatchReady' : IDL.Null,
    'qualityCheck' : IDL.Null,
    'stitching' : IDL.Null,
    'finishing' : IDL.Null,
    'cutting' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InventoryCategory = IDL.Variant({
    'other' : IDL.Null,
    'trim' : IDL.Null,
    'thread' : IDL.Null,
    'fabric' : IDL.Null,
  });
  const InventoryUnit = IDL.Variant({
    'kg' : IDL.Null,
    'meter' : IDL.Null,
    'roll' : IDL.Null,
    'piece' : IDL.Null,
  });
  const InventoryItemId = IDL.Nat;
  const JobWorkerId = IDL.Nat;
  const Time = IDL.Int;
  const JobWorkAssignmentId = IDL.Nat;
  const JobWorkerSpecialty = IDL.Variant({
    'embroidery' : IDL.Null,
    'both' : IDL.Null,
    'stitching' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const OrderId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
    'material' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : InventoryItemId,
    'name' : IDL.Text,
    'unit' : InventoryUnit,
    'lastUpdated' : Time,
    'category' : InventoryCategory,
    'reorderLevel' : IDL.Float64,
    'currentStock' : IDL.Float64,
  });
  const JobWorkAssignmentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'inProgress' : IDL.Null,
    'returned' : IDL.Null,
  });
  const JobWorkAssignment = IDL.Record({
    'id' : JobWorkAssignmentId,
    'productionJobId' : ProductionJobId,
    'status' : JobWorkAssignmentStatus,
    'actualReturnDate' : IDL.Opt(Time),
    'jobWorkerId' : JobWorkerId,
    'stage' : ProductionStage,
    'expectedReturnDate' : Time,
    'notes' : IDL.Text,
    'assignedDate' : Time,
  });
  const JobWorker = IDL.Record({
    'id' : JobWorkerId,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'isActive' : IDL.Bool,
    'specialty' : JobWorkerSpecialty,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'dispatched' : IDL.Null,
    'inProduction' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ProductOrder = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerContact' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Text,
    'deliveryDate' : IDL.Text,
    'productId' : ProductId,
    'orderType' : IDL.Variant({ 'MTO' : IDL.Null, 'readyStock' : IDL.Null }),
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'orderNumber' : IDL.Text,
    'styleName' : IDL.Text,
  });
  const StageHistoryEntry = IDL.Record({
    'completedAt' : Time,
    'stage' : ProductionStage,
  });
  const ProductionJob = IDL.Record({
    'id' : ProductionJobId,
    'startedAt' : Time,
    'isCompleted' : IDL.Bool,
    'stageHistory' : IDL.Vec(StageHistoryEntry),
    'orderId' : OrderId,
    'currentStage' : ProductionStage,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'advanceProductionJobStage' : IDL.Func(
        [ProductionJobId, ProductionStage],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInventoryItem' : IDL.Func(
        [IDL.Text, InventoryCategory, InventoryUnit, IDL.Float64, IDL.Float64],
        [InventoryItemId],
        [],
      ),
    'createJobWorkAssignment' : IDL.Func(
        [ProductionJobId, ProductionStage, JobWorkerId, Time, Time, IDL.Text],
        [JobWorkAssignmentId],
        [],
      ),
    'createJobWorker' : IDL.Func(
        [IDL.Text, JobWorkerSpecialty, IDL.Text, IDL.Text, IDL.Text],
        [JobWorkerId],
        [],
      ),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Variant({ 'MTO' : IDL.Null, 'readyStock' : IDL.Null }),
          IDL.Text,
          IDL.Text,
        ],
        [OrderId],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
        [ProductId],
        [],
      ),
    'createProductionJob' : IDL.Func(
        [OrderId, ProductionStage],
        [ProductionJobId],
        [],
      ),
    'deleteInventoryItem' : IDL.Func([InventoryItemId], [], []),
    'deleteJobWorkAssignment' : IDL.Func([JobWorkAssignmentId], [], []),
    'deleteJobWorker' : IDL.Func([JobWorkerId], [], []),
    'deleteOrder' : IDL.Func([OrderId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteProductionJob' : IDL.Func([ProductionJobId], [], []),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllJobWorkAssignments' : IDL.Func(
        [],
        [IDL.Vec(JobWorkAssignment)],
        ['query'],
      ),
    'getAllJobWorkers' : IDL.Func([], [IDL.Vec(JobWorker)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(ProductOrder)], ['query']),
    'getAllProductionJobs' : IDL.Func([], [IDL.Vec(ProductionJob)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInventoryItem' : IDL.Func(
        [InventoryItemId],
        [InventoryItem],
        ['query'],
      ),
    'getJobWorkAssignment' : IDL.Func(
        [JobWorkAssignmentId],
        [JobWorkAssignment],
        ['query'],
      ),
    'getJobWorkAssignmentsByJobAndWorker' : IDL.Func(
        [ProductionJobId, JobWorkerId],
        [IDL.Vec(JobWorkAssignment)],
        ['query'],
      ),
    'getJobWorker' : IDL.Func([JobWorkerId], [JobWorker], ['query']),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getOrder' : IDL.Func([OrderId], [ProductOrder], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(ProductOrder)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductionJob' : IDL.Func(
        [ProductionJobId],
        [ProductionJob],
        ['query'],
      ),
    'getProductionJobsByOrderId' : IDL.Func(
        [OrderId],
        [IDL.Vec(ProductionJob)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInventoryItem' : IDL.Func([InventoryItem], [], []),
    'updateJobWorkAssignment' : IDL.Func([JobWorkAssignment], [], []),
    'updateJobWorker' : IDL.Func([JobWorker], [], []),
    'updateOrder' : IDL.Func([ProductOrder], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateProductionJob' : IDL.Func([ProductionJob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };