/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface ProductOrder {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    customerContact: string;
    createdAt: Time;
    size: string;
    deliveryDate: string;
    productId: ProductId;
    orderType: Variant_MTO_readyStock;
    notes: string;
    quantity: bigint;
    orderNumber: string;
    styleName: string;
}
export type Time = bigint;
export interface ProductionJob {
    id: ProductionJobId;
    startedAt: Time;
    isCompleted: boolean;
    stageHistory: Array<StageHistoryEntry>;
    orderId: OrderId;
    currentStage: ProductionStage;
}
export interface StageHistoryEntry {
    completedAt: Time;
    stage: ProductionStage;
}
export type ProductionJobId = bigint;
export interface JobWorkAssignment {
    id: JobWorkAssignmentId;
    productionJobId: ProductionJobId;
    status: JobWorkAssignmentStatus;
    actualReturnDate?: Time;
    jobWorkerId: JobWorkerId;
    stage: ProductionStage;
    expectedReturnDate: Time;
    notes: string;
    assignedDate: Time;
}
export type JobWorkAssignmentId = bigint;
export type InventoryItemId = bigint;
export interface InventoryItem {
    id: InventoryItemId;
    name: string;
    unit: InventoryUnit;
    lastUpdated: Time;
    category: InventoryCategory;
    reorderLevel: number;
    currentStock: number;
}
export interface JobWorker {
    id: JobWorkerId;
    name: string;
    contactPerson: string;
    isActive: boolean;
    specialty: JobWorkerSpecialty;
    phone: string;
    location: string;
}
export type JobWorkerId = bigint;
export type ProductId = bigint;
export interface Product {
    id: ProductId;
    name: string;
    isActive: boolean;
    sizes: Array<string>;
    category: string;
    basePrice: bigint;
    material: string;
}
export type OrderId = bigint;
export enum InventoryCategory {
    other = "other",
    trim = "trim",
    thread = "thread",
    fabric = "fabric"
}
export enum InventoryUnit {
    kg = "kg",
    meter = "meter",
    roll = "roll",
    piece = "piece"
}
export enum JobWorkAssignmentStatus {
    pending = "pending",
    rejected = "rejected",
    inProgress = "inProgress",
    returned = "returned"
}
export enum JobWorkerSpecialty {
    embroidery = "embroidery",
    both = "both",
    stitching = "stitching"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    dispatched = "dispatched",
    inProduction = "inProduction",
    confirmed = "confirmed"
}
export enum ProductionStage {
    embroidery = "embroidery",
    dispatchReady = "dispatchReady",
    qualityCheck = "qualityCheck",
    stitching = "stitching",
    finishing = "finishing",
    cutting = "cutting"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_MTO_readyStock {
    MTO = "MTO",
    readyStock = "readyStock"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    advanceProductionJobStage(jobId: ProductionJobId, newStage: ProductionStage): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createInventoryItem(name: string, category: InventoryCategory, unit: InventoryUnit, currentStock: number, reorderLevel: number): Promise<InventoryItemId>;
    createJobWorkAssignment(productionJobId: ProductionJobId, stage: ProductionStage, jobWorkerId: JobWorkerId, assignedDate: Time, expectedReturnDate: Time, notes: string): Promise<JobWorkAssignmentId>;
    createJobWorker(name: string, specialty: JobWorkerSpecialty, contactPerson: string, phone: string, location: string): Promise<JobWorkerId>;
    createOrder(orderNumber: string, customerName: string, customerContact: string, productId: ProductId, styleName: string, size: string, quantity: bigint, orderType: Variant_MTO_readyStock, deliveryDate: string, notes: string): Promise<OrderId>;
    createProduct(name: string, category: string, sizes: Array<string>, material: string, basePrice: bigint): Promise<ProductId>;
    createProductionJob(orderId: OrderId, currentStage: ProductionStage): Promise<ProductionJobId>;
    deleteInventoryItem(inventoryId: InventoryItemId): Promise<void>;
    deleteJobWorkAssignment(assignmentId: JobWorkAssignmentId): Promise<void>;
    deleteJobWorker(jobWorkerId: JobWorkerId): Promise<void>;
    deleteOrder(orderId: OrderId): Promise<void>;
    deleteProduct(productId: ProductId): Promise<void>;
    deleteProductionJob(jobId: ProductionJobId): Promise<void>;
    getActiveProducts(): Promise<Array<Product>>;
    getAllInventoryItems(): Promise<Array<InventoryItem>>;
    getAllJobWorkAssignments(): Promise<Array<JobWorkAssignment>>;
    getAllJobWorkers(): Promise<Array<JobWorker>>;
    getAllOrders(): Promise<Array<ProductOrder>>;
    getAllProductionJobs(): Promise<Array<ProductionJob>>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInventoryItem(inventoryId: InventoryItemId): Promise<InventoryItem>;
    getJobWorkAssignment(assignmentId: JobWorkAssignmentId): Promise<JobWorkAssignment>;
    getJobWorkAssignmentsByJobAndWorker(productionJobId: ProductionJobId, jobWorkerId: JobWorkerId): Promise<Array<JobWorkAssignment>>;
    getJobWorker(jobWorkerId: JobWorkerId): Promise<JobWorker>;
    getLowStockItems(): Promise<Array<InventoryItem>>;
    getOrder(orderId: OrderId): Promise<ProductOrder>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<ProductOrder>>;
    getProduct(productId: ProductId): Promise<Product>;
    getProductionJob(jobId: ProductionJobId): Promise<ProductionJob>;
    getProductionJobsByOrderId(orderId: OrderId): Promise<Array<ProductionJob>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateInventoryItem(item: InventoryItem): Promise<void>;
    updateJobWorkAssignment(assignment: JobWorkAssignment): Promise<void>;
    updateJobWorker(worker: JobWorker): Promise<void>;
    updateOrder(order: ProductOrder): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateProductionJob(job: ProductionJob): Promise<void>;
}
import type { InventoryCategory as _InventoryCategory, InventoryItem as _InventoryItem, InventoryItemId as _InventoryItemId, InventoryUnit as _InventoryUnit, JobWorkAssignment as _JobWorkAssignment, JobWorkAssignmentId as _JobWorkAssignmentId, JobWorkAssignmentStatus as _JobWorkAssignmentStatus, JobWorker as _JobWorker, JobWorkerId as _JobWorkerId, JobWorkerSpecialty as _JobWorkerSpecialty, OrderId as _OrderId, OrderStatus as _OrderStatus, ProductId as _ProductId, ProductOrder as _ProductOrder, ProductionJob as _ProductionJob, ProductionJobId as _ProductionJobId, ProductionStage as _ProductionStage, StageHistoryEntry as _StageHistoryEntry, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async advanceProductionJobStage(arg0: ProductionJobId, arg1: ProductionStage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.advanceProductionJobStage(arg0, to_candid_ProductionStage_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advanceProductionJobStage(arg0, to_candid_ProductionStage_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createInventoryItem(arg0: string, arg1: InventoryCategory, arg2: InventoryUnit, arg3: number, arg4: number): Promise<InventoryItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryItem(arg0, to_candid_InventoryCategory_n5(this._uploadFile, this._downloadFile, arg1), to_candid_InventoryUnit_n7(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryItem(arg0, to_candid_InventoryCategory_n5(this._uploadFile, this._downloadFile, arg1), to_candid_InventoryUnit_n7(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createJobWorkAssignment(arg0: ProductionJobId, arg1: ProductionStage, arg2: JobWorkerId, arg3: Time, arg4: Time, arg5: string): Promise<JobWorkAssignmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobWorkAssignment(arg0, to_candid_ProductionStage_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobWorkAssignment(arg0, to_candid_ProductionStage_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createJobWorker(arg0: string, arg1: JobWorkerSpecialty, arg2: string, arg3: string, arg4: string): Promise<JobWorkerId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobWorker(arg0, to_candid_JobWorkerSpecialty_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobWorker(arg0, to_candid_JobWorkerSpecialty_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: string, arg3: ProductId, arg4: string, arg5: string, arg6: bigint, arg7: Variant_MTO_readyStock, arg8: string, arg9: string): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_variant_n11(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_variant_n11(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
            return result;
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: Array<string>, arg3: string, arg4: bigint): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createProductionJob(arg0: OrderId, arg1: ProductionStage): Promise<ProductionJobId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProductionJob(arg0, to_candid_ProductionStage_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProductionJob(arg0, to_candid_ProductionStage_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteInventoryItem(arg0: InventoryItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteJobWorkAssignment(arg0: JobWorkAssignmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobWorkAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobWorkAssignment(arg0);
            return result;
        }
    }
    async deleteJobWorker(arg0: JobWorkerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobWorker(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: OrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteProductionJob(arg0: ProductionJobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductionJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductionJob(arg0);
            return result;
        }
    }
    async getActiveProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProducts();
            return result;
        }
    }
    async getAllInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryItems();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryItems();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobWorkAssignments(): Promise<Array<JobWorkAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobWorkAssignments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobWorkAssignments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobWorkers(): Promise<Array<JobWorker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobWorkers();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobWorkers();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<ProductOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProductionJobs(): Promise<Array<ProductionJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductionJobs();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductionJobs();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItem(arg0: InventoryItemId): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_InventoryItem_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_InventoryItem_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobWorkAssignment(arg0: JobWorkAssignmentId): Promise<JobWorkAssignment> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobWorkAssignment(arg0);
                return from_candid_JobWorkAssignment_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobWorkAssignment(arg0);
            return from_candid_JobWorkAssignment_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobWorkAssignmentsByJobAndWorker(arg0: ProductionJobId, arg1: JobWorkerId): Promise<Array<JobWorkAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobWorkAssignmentsByJobAndWorker(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobWorkAssignmentsByJobAndWorker(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobWorker(arg0: JobWorkerId): Promise<JobWorker> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobWorker(arg0);
                return from_candid_JobWorker_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobWorker(arg0);
            return from_candid_JobWorker_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockItems();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockItems();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<ProductOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_ProductOrder_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_ProductOrder_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<ProductOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return result;
        }
    }
    async getProductionJob(arg0: ProductionJobId): Promise<ProductionJob> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionJob(arg0);
                return from_candid_ProductionJob_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionJob(arg0);
            return from_candid_ProductionJob_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductionJobsByOrderId(arg0: OrderId): Promise<Array<ProductionJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionJobsByOrderId(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionJobsByOrderId(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(to_candid_InventoryItem_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(to_candid_InventoryItem_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJobWorkAssignment(arg0: JobWorkAssignment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobWorkAssignment(to_candid_JobWorkAssignment_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobWorkAssignment(to_candid_JobWorkAssignment_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJobWorker(arg0: JobWorker): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobWorker(to_candid_JobWorker_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobWorker(to_candid_JobWorker_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrder(arg0: ProductOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(to_candid_ProductOrder_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(to_candid_ProductOrder_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
    async updateProductionJob(arg0: ProductionJob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductionJob(to_candid_ProductionJob_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductionJob(to_candid_ProductionJob_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_InventoryCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryCategory): InventoryCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryUnit_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryUnit): InventoryUnit {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_JobWorkAssignmentStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobWorkAssignmentStatus): JobWorkAssignmentStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_JobWorkAssignment_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobWorkAssignment): JobWorkAssignment {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_JobWorkerSpecialty_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobWorkerSpecialty): JobWorkerSpecialty {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_JobWorker_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobWorker): JobWorker {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ProductOrder_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductOrder): ProductOrder {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ProductionJob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductionJob): ProductionJob {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_ProductionStage_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductionStage): ProductionStage {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StageHistoryEntry_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StageHistoryEntry): StageHistoryEntry {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InventoryItemId;
    name: string;
    unit: _InventoryUnit;
    lastUpdated: _Time;
    category: _InventoryCategory;
    reorderLevel: number;
    currentStock: number;
}): {
    id: InventoryItemId;
    name: string;
    unit: InventoryUnit;
    lastUpdated: Time;
    category: InventoryCategory;
    reorderLevel: number;
    currentStock: number;
} {
    return {
        id: value.id,
        name: value.name,
        unit: from_candid_InventoryUnit_n15(_uploadFile, _downloadFile, value.unit),
        lastUpdated: value.lastUpdated,
        category: from_candid_InventoryCategory_n17(_uploadFile, _downloadFile, value.category),
        reorderLevel: value.reorderLevel,
        currentStock: value.currentStock
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobWorkAssignmentId;
    productionJobId: _ProductionJobId;
    status: _JobWorkAssignmentStatus;
    actualReturnDate: [] | [_Time];
    jobWorkerId: _JobWorkerId;
    stage: _ProductionStage;
    expectedReturnDate: _Time;
    notes: string;
    assignedDate: _Time;
}): {
    id: JobWorkAssignmentId;
    productionJobId: ProductionJobId;
    status: JobWorkAssignmentStatus;
    actualReturnDate?: Time;
    jobWorkerId: JobWorkerId;
    stage: ProductionStage;
    expectedReturnDate: Time;
    notes: string;
    assignedDate: Time;
} {
    return {
        id: value.id,
        productionJobId: value.productionJobId,
        status: from_candid_JobWorkAssignmentStatus_n22(_uploadFile, _downloadFile, value.status),
        actualReturnDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.actualReturnDate)),
        jobWorkerId: value.jobWorkerId,
        stage: from_candid_ProductionStage_n25(_uploadFile, _downloadFile, value.stage),
        expectedReturnDate: value.expectedReturnDate,
        notes: value.notes,
        assignedDate: value.assignedDate
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobWorkerId;
    name: string;
    contactPerson: string;
    isActive: boolean;
    specialty: _JobWorkerSpecialty;
    phone: string;
    location: string;
}): {
    id: JobWorkerId;
    name: string;
    contactPerson: string;
    isActive: boolean;
    specialty: JobWorkerSpecialty;
    phone: string;
    location: string;
} {
    return {
        id: value.id,
        name: value.name,
        contactPerson: value.contactPerson,
        isActive: value.isActive,
        specialty: from_candid_JobWorkerSpecialty_n30(_uploadFile, _downloadFile, value.specialty),
        phone: value.phone,
        location: value.location
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    customerContact: string;
    createdAt: _Time;
    size: string;
    deliveryDate: string;
    productId: _ProductId;
    orderType: {
        MTO: null;
    } | {
        readyStock: null;
    };
    notes: string;
    quantity: bigint;
    orderNumber: string;
    styleName: string;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    customerContact: string;
    createdAt: Time;
    size: string;
    deliveryDate: string;
    productId: ProductId;
    orderType: Variant_MTO_readyStock;
    notes: string;
    quantity: bigint;
    orderNumber: string;
    styleName: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n35(_uploadFile, _downloadFile, value.status),
        customerContact: value.customerContact,
        createdAt: value.createdAt,
        size: value.size,
        deliveryDate: value.deliveryDate,
        productId: value.productId,
        orderType: from_candid_variant_n37(_uploadFile, _downloadFile, value.orderType),
        notes: value.notes,
        quantity: value.quantity,
        orderNumber: value.orderNumber,
        styleName: value.styleName
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductionJobId;
    startedAt: _Time;
    isCompleted: boolean;
    stageHistory: Array<_StageHistoryEntry>;
    orderId: _OrderId;
    currentStage: _ProductionStage;
}): {
    id: ProductionJobId;
    startedAt: Time;
    isCompleted: boolean;
    stageHistory: Array<StageHistoryEntry>;
    orderId: OrderId;
    currentStage: ProductionStage;
} {
    return {
        id: value.id,
        startedAt: value.startedAt,
        isCompleted: value.isCompleted,
        stageHistory: from_candid_vec_n41(_uploadFile, _downloadFile, value.stageHistory),
        orderId: value.orderId,
        currentStage: from_candid_ProductionStage_n25(_uploadFile, _downloadFile, value.currentStage)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: _Time;
    stage: _ProductionStage;
}): {
    completedAt: Time;
    stage: ProductionStage;
} {
    return {
        completedAt: value.completedAt,
        stage: from_candid_ProductionStage_n25(_uploadFile, _downloadFile, value.stage)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kg: null;
} | {
    meter: null;
} | {
    roll: null;
} | {
    piece: null;
}): InventoryUnit {
    return "kg" in value ? InventoryUnit.kg : "meter" in value ? InventoryUnit.meter : "roll" in value ? InventoryUnit.roll : "piece" in value ? InventoryUnit.piece : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    trim: null;
} | {
    thread: null;
} | {
    fabric: null;
}): InventoryCategory {
    return "other" in value ? InventoryCategory.other : "trim" in value ? InventoryCategory.trim : "thread" in value ? InventoryCategory.thread : "fabric" in value ? InventoryCategory.fabric : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    inProgress: null;
} | {
    returned: null;
}): JobWorkAssignmentStatus {
    return "pending" in value ? JobWorkAssignmentStatus.pending : "rejected" in value ? JobWorkAssignmentStatus.rejected : "inProgress" in value ? JobWorkAssignmentStatus.inProgress : "returned" in value ? JobWorkAssignmentStatus.returned : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    embroidery: null;
} | {
    dispatchReady: null;
} | {
    qualityCheck: null;
} | {
    stitching: null;
} | {
    finishing: null;
} | {
    cutting: null;
}): ProductionStage {
    return "embroidery" in value ? ProductionStage.embroidery : "dispatchReady" in value ? ProductionStage.dispatchReady : "qualityCheck" in value ? ProductionStage.qualityCheck : "stitching" in value ? ProductionStage.stitching : "finishing" in value ? ProductionStage.finishing : "cutting" in value ? ProductionStage.cutting : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    embroidery: null;
} | {
    both: null;
} | {
    stitching: null;
}): JobWorkerSpecialty {
    return "embroidery" in value ? JobWorkerSpecialty.embroidery : "both" in value ? JobWorkerSpecialty.both : "stitching" in value ? JobWorkerSpecialty.stitching : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    dispatched: null;
} | {
    inProduction: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "dispatched" in value ? OrderStatus.dispatched : "inProduction" in value ? OrderStatus.inProduction : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MTO: null;
} | {
    readyStock: null;
}): Variant_MTO_readyStock {
    return "MTO" in value ? Variant_MTO_readyStock.MTO : "readyStock" in value ? Variant_MTO_readyStock.readyStock : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobWorkAssignment>): Array<JobWorkAssignment> {
    return value.map((x)=>from_candid_JobWorkAssignment_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobWorker>): Array<JobWorker> {
    return value.map((x)=>from_candid_JobWorker_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductOrder>): Array<ProductOrder> {
    return value.map((x)=>from_candid_ProductOrder_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductionJob>): Array<ProductionJob> {
    return value.map((x)=>from_candid_ProductionJob_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StageHistoryEntry>): Array<StageHistoryEntry> {
    return value.map((x)=>from_candid_StageHistoryEntry_n42(_uploadFile, _downloadFile, x));
}
function to_candid_InventoryCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryCategory): _InventoryCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryItem_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryItem): _InventoryItem {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryUnit_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryUnit): _InventoryUnit {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_JobWorkAssignmentStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobWorkAssignmentStatus): _JobWorkAssignmentStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_JobWorkAssignment_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobWorkAssignment): _JobWorkAssignment {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_JobWorkerSpecialty_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobWorkerSpecialty): _JobWorkerSpecialty {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_JobWorker_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobWorker): _JobWorker {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_ProductOrder_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductOrder): _ProductOrder {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_ProductionJob_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductionJob): _ProductionJob {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_ProductionStage_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductionStage): _ProductionStage {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_StageHistoryEntry_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StageHistoryEntry): _StageHistoryEntry {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: InventoryItemId;
    name: string;
    unit: InventoryUnit;
    lastUpdated: Time;
    category: InventoryCategory;
    reorderLevel: number;
    currentStock: number;
}): {
    id: _InventoryItemId;
    name: string;
    unit: _InventoryUnit;
    lastUpdated: _Time;
    category: _InventoryCategory;
    reorderLevel: number;
    currentStock: number;
} {
    return {
        id: value.id,
        name: value.name,
        unit: to_candid_InventoryUnit_n7(_uploadFile, _downloadFile, value.unit),
        lastUpdated: value.lastUpdated,
        category: to_candid_InventoryCategory_n5(_uploadFile, _downloadFile, value.category),
        reorderLevel: value.reorderLevel,
        currentStock: value.currentStock
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: JobWorkAssignmentId;
    productionJobId: ProductionJobId;
    status: JobWorkAssignmentStatus;
    actualReturnDate?: Time;
    jobWorkerId: JobWorkerId;
    stage: ProductionStage;
    expectedReturnDate: Time;
    notes: string;
    assignedDate: Time;
}): {
    id: _JobWorkAssignmentId;
    productionJobId: _ProductionJobId;
    status: _JobWorkAssignmentStatus;
    actualReturnDate: [] | [_Time];
    jobWorkerId: _JobWorkerId;
    stage: _ProductionStage;
    expectedReturnDate: _Time;
    notes: string;
    assignedDate: _Time;
} {
    return {
        id: value.id,
        productionJobId: value.productionJobId,
        status: to_candid_JobWorkAssignmentStatus_n53(_uploadFile, _downloadFile, value.status),
        actualReturnDate: value.actualReturnDate ? candid_some(value.actualReturnDate) : candid_none(),
        jobWorkerId: value.jobWorkerId,
        stage: to_candid_ProductionStage_n1(_uploadFile, _downloadFile, value.stage),
        expectedReturnDate: value.expectedReturnDate,
        notes: value.notes,
        assignedDate: value.assignedDate
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: JobWorkerId;
    name: string;
    contactPerson: string;
    isActive: boolean;
    specialty: JobWorkerSpecialty;
    phone: string;
    location: string;
}): {
    id: _JobWorkerId;
    name: string;
    contactPerson: string;
    isActive: boolean;
    specialty: _JobWorkerSpecialty;
    phone: string;
    location: string;
} {
    return {
        id: value.id,
        name: value.name,
        contactPerson: value.contactPerson,
        isActive: value.isActive,
        specialty: to_candid_JobWorkerSpecialty_n9(_uploadFile, _downloadFile, value.specialty),
        phone: value.phone,
        location: value.location
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    customerContact: string;
    createdAt: Time;
    size: string;
    deliveryDate: string;
    productId: ProductId;
    orderType: Variant_MTO_readyStock;
    notes: string;
    quantity: bigint;
    orderNumber: string;
    styleName: string;
}): {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    customerContact: string;
    createdAt: _Time;
    size: string;
    deliveryDate: string;
    productId: _ProductId;
    orderType: {
        MTO: null;
    } | {
        readyStock: null;
    };
    notes: string;
    quantity: bigint;
    orderNumber: string;
    styleName: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_OrderStatus_n47(_uploadFile, _downloadFile, value.status),
        customerContact: value.customerContact,
        createdAt: value.createdAt,
        size: value.size,
        deliveryDate: value.deliveryDate,
        productId: value.productId,
        orderType: to_candid_variant_n11(_uploadFile, _downloadFile, value.orderType),
        notes: value.notes,
        quantity: value.quantity,
        orderNumber: value.orderNumber,
        styleName: value.styleName
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductionJobId;
    startedAt: Time;
    isCompleted: boolean;
    stageHistory: Array<StageHistoryEntry>;
    orderId: OrderId;
    currentStage: ProductionStage;
}): {
    id: _ProductionJobId;
    startedAt: _Time;
    isCompleted: boolean;
    stageHistory: Array<_StageHistoryEntry>;
    orderId: _OrderId;
    currentStage: _ProductionStage;
} {
    return {
        id: value.id,
        startedAt: value.startedAt,
        isCompleted: value.isCompleted,
        stageHistory: to_candid_vec_n61(_uploadFile, _downloadFile, value.stageHistory),
        orderId: value.orderId,
        currentStage: to_candid_ProductionStage_n1(_uploadFile, _downloadFile, value.currentStage)
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: Time;
    stage: ProductionStage;
}): {
    completedAt: _Time;
    stage: _ProductionStage;
} {
    return {
        completedAt: value.completedAt,
        stage: to_candid_ProductionStage_n1(_uploadFile, _downloadFile, value.stage)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobWorkerSpecialty): {
    embroidery: null;
} | {
    both: null;
} | {
    stitching: null;
} {
    return value == JobWorkerSpecialty.embroidery ? {
        embroidery: null
    } : value == JobWorkerSpecialty.both ? {
        both: null
    } : value == JobWorkerSpecialty.stitching ? {
        stitching: null
    } : value;
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_MTO_readyStock): {
    MTO: null;
} | {
    readyStock: null;
} {
    return value == Variant_MTO_readyStock.MTO ? {
        MTO: null
    } : value == Variant_MTO_readyStock.readyStock ? {
        readyStock: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductionStage): {
    embroidery: null;
} | {
    dispatchReady: null;
} | {
    qualityCheck: null;
} | {
    stitching: null;
} | {
    finishing: null;
} | {
    cutting: null;
} {
    return value == ProductionStage.embroidery ? {
        embroidery: null
    } : value == ProductionStage.dispatchReady ? {
        dispatchReady: null
    } : value == ProductionStage.qualityCheck ? {
        qualityCheck: null
    } : value == ProductionStage.stitching ? {
        stitching: null
    } : value == ProductionStage.finishing ? {
        finishing: null
    } : value == ProductionStage.cutting ? {
        cutting: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    dispatched: null;
} | {
    inProduction: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.dispatched ? {
        dispatched: null
    } : value == OrderStatus.inProduction ? {
        inProduction: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobWorkAssignmentStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    inProgress: null;
} | {
    returned: null;
} {
    return value == JobWorkAssignmentStatus.pending ? {
        pending: null
    } : value == JobWorkAssignmentStatus.rejected ? {
        rejected: null
    } : value == JobWorkAssignmentStatus.inProgress ? {
        inProgress: null
    } : value == JobWorkAssignmentStatus.returned ? {
        returned: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryCategory): {
    other: null;
} | {
    trim: null;
} | {
    thread: null;
} | {
    fabric: null;
} {
    return value == InventoryCategory.other ? {
        other: null
    } : value == InventoryCategory.trim ? {
        trim: null
    } : value == InventoryCategory.thread ? {
        thread: null
    } : value == InventoryCategory.fabric ? {
        fabric: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryUnit): {
    kg: null;
} | {
    meter: null;
} | {
    roll: null;
} | {
    piece: null;
} {
    return value == InventoryUnit.kg ? {
        kg: null
    } : value == InventoryUnit.meter ? {
        meter: null
    } : value == InventoryUnit.roll ? {
        roll: null
    } : value == InventoryUnit.piece ? {
        piece: null
    } : value;
}
function to_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StageHistoryEntry>): Array<_StageHistoryEntry> {
    return value.map((x)=>to_candid_StageHistoryEntry_n62(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
